sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build -t boom .

script:
    - docker run -i boom https://www.google.com/ > result  

    - echo "==> Validating the test results..."
    - sh -c "[ -s result ]"